apiVersion: apps/v1
kind: Deployment
metadata:
  name: una-assignment-deployment
  labels:
    app: una-assignment-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: una-assignment-app
  template:
    metadata:
      labels:
        app: una-assignment-app
    spec:
      containers:
      - name: color-app
        image: fauzancloud/color-app:v1
        ports:
        - containerPort: 5000
        env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: una-assignment-configmap
              key: APP_COLOR
        resources:
          requests:
            cpu: "10m" # 1% dari 1 core karena aplikasi juga ringan
            memory: "8Mi" # penggunaan memori kecil juga
          limits:
            cpu: "333m"    # Hasil bagi dari 1 Core atau 1000m dibagi 3 Replica
            memory: "42Mi" # Hasil bagi dari 128MB dibagi 3 Replica
